# Generated by Django 4.1.3 on 2022-11-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
